services:
  db:
    image: postgres:15
    restart: always
    healthcheck:
      test: ["CMD", "pg_isready", "-U", "${DB_USER}", "-d", "${DB_NAME}"]
      interval: 5s
      timeout: 5s
      retries: 5
    environment:
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_DB: ${DB_NAME}
    volumes:
      - db_data:/var/lib/postgresql/data
    ports:
      - "5433:5432"  # ✅ Ubah host port jadi 5433

  api:
    build:
      context: .
      dockerfile: Dockerfile
    depends_on:
      db:
        condition: service_healthy
    ports:
      - "8081:8080" # ✅ Ubah host port jadi 8081
    volumes:
      - ./uploads:/app/uploads
    environment:
      DB_HOST: db
      DB_PORT: 5432
      DB_USER: ${DB_USER}
      DB_PASSWORD: ${DB_PASSWORD}
      DB_NAME: ${DB_NAME}
    env_file:
      - .env

  prometheus:
    image: prom/prometheus
    ports:
      - "9091:9090" # ✅ Ubah host port jadi 9091
    volumes:
      - ./prometheus.yml:/etc/prometheus/prometheus.yml

  redis:
    image: redis:7
    restart: always
    ports:
      - "6380:6379" # ✅ Ubah host port jadi 6380
    command: redis-server --appendonly yes
    volumes:
      - redis_data:/data

volumes:
  db_data:
  redis_data:
